/**
 * 用于管理action常量的模块
 */
export const SET_HOMEDATA = 'SET_HOMEDATA';
export const SET_CATEGORYLIST = 'SET_CATEGORYLIST';
export const SET_RECOMMEND_TABS = 'SET_RECOMMEND_TABS';
export const SET_RECOMMEND_DATA = 'SET_RECOMMEND_DATA';
export const SET_AUTO_RECOMMEND = 'SET_ATUO_RECOMMEND';
export const SET_ORDERSHOW_TOP = 'SET_ORDERSHOW_TOP';
export const SET_ORDERSHOW_RATINGS = 'SET_ORDERSHOW_RATINGS';
